// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/recipes.proto

package com.gb.recipes;

public final class RecipeInformation {
  private RecipeInformation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecipeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:recipes.Recipe)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 prep_time = 3;</code>
     */
    int getPrepTime();

    /**
     * <code>int32 cook_time = 4;</code>
     */
    int getCookTime();

    /**
     * <code>int32 rating = 5;</code>
     */
    int getRating();

    /**
     * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
     */
    java.util.List<com.gb.recipes.RecipeInformation.Recipe.Ingredient> 
        getIngredientsList();
    /**
     * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
     */
    com.gb.recipes.RecipeInformation.Recipe.Ingredient getIngredients(int index);
    /**
     * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
     */
    int getIngredientsCount();
    /**
     * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
     */
    java.util.List<? extends com.gb.recipes.RecipeInformation.Recipe.IngredientOrBuilder> 
        getIngredientsOrBuilderList();
    /**
     * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
     */
    com.gb.recipes.RecipeInformation.Recipe.IngredientOrBuilder getIngredientsOrBuilder(
        int index);

    /**
     * <code>.recipes.Recipe.Cuisine cuisine = 7;</code>
     */
    int getCuisineValue();
    /**
     * <code>.recipes.Recipe.Cuisine cuisine = 7;</code>
     */
    com.gb.recipes.RecipeInformation.Recipe.Cuisine getCuisine();
  }
  /**
   * Protobuf type {@code recipes.Recipe}
   */
  public  static final class Recipe extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:recipes.Recipe)
      RecipeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Recipe.newBuilder() to construct.
    private Recipe(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Recipe() {
      id_ = 0;
      name_ = "";
      prepTime_ = 0;
      cookTime_ = 0;
      rating_ = 0;
      ingredients_ = java.util.Collections.emptyList();
      cuisine_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Recipe(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              prepTime_ = input.readInt32();
              break;
            }
            case 32: {

              cookTime_ = input.readInt32();
              break;
            }
            case 40: {

              rating_ = input.readInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                ingredients_ = new java.util.ArrayList<com.gb.recipes.RecipeInformation.Recipe.Ingredient>();
                mutable_bitField0_ |= 0x00000020;
              }
              ingredients_.add(
                  input.readMessage(com.gb.recipes.RecipeInformation.Recipe.Ingredient.parser(), extensionRegistry));
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              cuisine_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          ingredients_ = java.util.Collections.unmodifiableList(ingredients_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gb.recipes.RecipeInformation.internal_static_recipes_Recipe_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gb.recipes.RecipeInformation.internal_static_recipes_Recipe_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gb.recipes.RecipeInformation.Recipe.class, com.gb.recipes.RecipeInformation.Recipe.Builder.class);
    }

    /**
     * Protobuf enum {@code recipes.Recipe.IngredientMeasure}
     */
    public enum IngredientMeasure
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>EACH = 0;</code>
       */
      EACH(0),
      /**
       * <code>OUCES = 1;</code>
       */
      OUCES(1),
      /**
       * <code>LBS = 2;</code>
       */
      LBS(2),
      /**
       * <code>GRAMS = 3;</code>
       */
      GRAMS(3),
      /**
       * <code>ML = 4;</code>
       */
      ML(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>EACH = 0;</code>
       */
      public static final int EACH_VALUE = 0;
      /**
       * <code>OUCES = 1;</code>
       */
      public static final int OUCES_VALUE = 1;
      /**
       * <code>LBS = 2;</code>
       */
      public static final int LBS_VALUE = 2;
      /**
       * <code>GRAMS = 3;</code>
       */
      public static final int GRAMS_VALUE = 3;
      /**
       * <code>ML = 4;</code>
       */
      public static final int ML_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static IngredientMeasure valueOf(int value) {
        return forNumber(value);
      }

      public static IngredientMeasure forNumber(int value) {
        switch (value) {
          case 0: return EACH;
          case 1: return OUCES;
          case 2: return LBS;
          case 3: return GRAMS;
          case 4: return ML;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<IngredientMeasure>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          IngredientMeasure> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<IngredientMeasure>() {
              public IngredientMeasure findValueByNumber(int number) {
                return IngredientMeasure.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.gb.recipes.RecipeInformation.Recipe.getDescriptor().getEnumTypes().get(0);
      }

      private static final IngredientMeasure[] VALUES = values();

      public static IngredientMeasure valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private IngredientMeasure(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:recipes.Recipe.IngredientMeasure)
    }

    /**
     * Protobuf enum {@code recipes.Recipe.Cuisine}
     */
    public enum Cuisine
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SOUTH_INDIAN = 0;</code>
       */
      SOUTH_INDIAN(0),
      /**
       * <code>NORTH_INDIAN = 1;</code>
       */
      NORTH_INDIAN(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SOUTH_INDIAN = 0;</code>
       */
      public static final int SOUTH_INDIAN_VALUE = 0;
      /**
       * <code>NORTH_INDIAN = 1;</code>
       */
      public static final int NORTH_INDIAN_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Cuisine valueOf(int value) {
        return forNumber(value);
      }

      public static Cuisine forNumber(int value) {
        switch (value) {
          case 0: return SOUTH_INDIAN;
          case 1: return NORTH_INDIAN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Cuisine>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Cuisine> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Cuisine>() {
              public Cuisine findValueByNumber(int number) {
                return Cuisine.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.gb.recipes.RecipeInformation.Recipe.getDescriptor().getEnumTypes().get(1);
      }

      private static final Cuisine[] VALUES = values();

      public static Cuisine valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Cuisine(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:recipes.Recipe.Cuisine)
    }

    public interface IngredientOrBuilder extends
        // @@protoc_insertion_point(interface_extends:recipes.Recipe.Ingredient)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>int32 quantity = 2;</code>
       */
      int getQuantity();

      /**
       * <code>.recipes.Recipe.IngredientMeasure measure = 3;</code>
       */
      int getMeasureValue();
      /**
       * <code>.recipes.Recipe.IngredientMeasure measure = 3;</code>
       */
      com.gb.recipes.RecipeInformation.Recipe.IngredientMeasure getMeasure();
    }
    /**
     * Protobuf type {@code recipes.Recipe.Ingredient}
     */
    public  static final class Ingredient extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:recipes.Recipe.Ingredient)
        IngredientOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Ingredient.newBuilder() to construct.
      private Ingredient(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Ingredient() {
        name_ = "";
        quantity_ = 0;
        measure_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Ingredient(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 16: {

                quantity_ = input.readInt32();
                break;
              }
              case 24: {
                int rawValue = input.readEnum();

                measure_ = rawValue;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gb.recipes.RecipeInformation.internal_static_recipes_Recipe_Ingredient_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gb.recipes.RecipeInformation.internal_static_recipes_Recipe_Ingredient_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gb.recipes.RecipeInformation.Recipe.Ingredient.class, com.gb.recipes.RecipeInformation.Recipe.Ingredient.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int QUANTITY_FIELD_NUMBER = 2;
      private int quantity_;
      /**
       * <code>int32 quantity = 2;</code>
       */
      public int getQuantity() {
        return quantity_;
      }

      public static final int MEASURE_FIELD_NUMBER = 3;
      private int measure_;
      /**
       * <code>.recipes.Recipe.IngredientMeasure measure = 3;</code>
       */
      public int getMeasureValue() {
        return measure_;
      }
      /**
       * <code>.recipes.Recipe.IngredientMeasure measure = 3;</code>
       */
      public com.gb.recipes.RecipeInformation.Recipe.IngredientMeasure getMeasure() {
        @SuppressWarnings("deprecation")
        com.gb.recipes.RecipeInformation.Recipe.IngredientMeasure result = com.gb.recipes.RecipeInformation.Recipe.IngredientMeasure.valueOf(measure_);
        return result == null ? com.gb.recipes.RecipeInformation.Recipe.IngredientMeasure.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (quantity_ != 0) {
          output.writeInt32(2, quantity_);
        }
        if (measure_ != com.gb.recipes.RecipeInformation.Recipe.IngredientMeasure.EACH.getNumber()) {
          output.writeEnum(3, measure_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (quantity_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, quantity_);
        }
        if (measure_ != com.gb.recipes.RecipeInformation.Recipe.IngredientMeasure.EACH.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(3, measure_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.gb.recipes.RecipeInformation.Recipe.Ingredient)) {
          return super.equals(obj);
        }
        com.gb.recipes.RecipeInformation.Recipe.Ingredient other = (com.gb.recipes.RecipeInformation.Recipe.Ingredient) obj;

        boolean result = true;
        result = result && getName()
            .equals(other.getName());
        result = result && (getQuantity()
            == other.getQuantity());
        result = result && measure_ == other.measure_;
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
        hash = (53 * hash) + getQuantity();
        hash = (37 * hash) + MEASURE_FIELD_NUMBER;
        hash = (53 * hash) + measure_;
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.gb.recipes.RecipeInformation.Recipe.Ingredient parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.gb.recipes.RecipeInformation.Recipe.Ingredient parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.gb.recipes.RecipeInformation.Recipe.Ingredient parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.gb.recipes.RecipeInformation.Recipe.Ingredient parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.gb.recipes.RecipeInformation.Recipe.Ingredient parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.gb.recipes.RecipeInformation.Recipe.Ingredient parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.gb.recipes.RecipeInformation.Recipe.Ingredient parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.gb.recipes.RecipeInformation.Recipe.Ingredient parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.gb.recipes.RecipeInformation.Recipe.Ingredient parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.gb.recipes.RecipeInformation.Recipe.Ingredient parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.gb.recipes.RecipeInformation.Recipe.Ingredient parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.gb.recipes.RecipeInformation.Recipe.Ingredient parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.gb.recipes.RecipeInformation.Recipe.Ingredient prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code recipes.Recipe.Ingredient}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:recipes.Recipe.Ingredient)
          com.gb.recipes.RecipeInformation.Recipe.IngredientOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.gb.recipes.RecipeInformation.internal_static_recipes_Recipe_Ingredient_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.gb.recipes.RecipeInformation.internal_static_recipes_Recipe_Ingredient_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.gb.recipes.RecipeInformation.Recipe.Ingredient.class, com.gb.recipes.RecipeInformation.Recipe.Ingredient.Builder.class);
        }

        // Construct using com.gb.recipes.RecipeInformation.Recipe.Ingredient.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          name_ = "";

          quantity_ = 0;

          measure_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.gb.recipes.RecipeInformation.internal_static_recipes_Recipe_Ingredient_descriptor;
        }

        @java.lang.Override
        public com.gb.recipes.RecipeInformation.Recipe.Ingredient getDefaultInstanceForType() {
          return com.gb.recipes.RecipeInformation.Recipe.Ingredient.getDefaultInstance();
        }

        @java.lang.Override
        public com.gb.recipes.RecipeInformation.Recipe.Ingredient build() {
          com.gb.recipes.RecipeInformation.Recipe.Ingredient result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.gb.recipes.RecipeInformation.Recipe.Ingredient buildPartial() {
          com.gb.recipes.RecipeInformation.Recipe.Ingredient result = new com.gb.recipes.RecipeInformation.Recipe.Ingredient(this);
          result.name_ = name_;
          result.quantity_ = quantity_;
          result.measure_ = measure_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.gb.recipes.RecipeInformation.Recipe.Ingredient) {
            return mergeFrom((com.gb.recipes.RecipeInformation.Recipe.Ingredient)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.gb.recipes.RecipeInformation.Recipe.Ingredient other) {
          if (other == com.gb.recipes.RecipeInformation.Recipe.Ingredient.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (other.getQuantity() != 0) {
            setQuantity(other.getQuantity());
          }
          if (other.measure_ != 0) {
            setMeasureValue(other.getMeasureValue());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.gb.recipes.RecipeInformation.Recipe.Ingredient parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.gb.recipes.RecipeInformation.Recipe.Ingredient) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private int quantity_ ;
        /**
         * <code>int32 quantity = 2;</code>
         */
        public int getQuantity() {
          return quantity_;
        }
        /**
         * <code>int32 quantity = 2;</code>
         */
        public Builder setQuantity(int value) {
          
          quantity_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 quantity = 2;</code>
         */
        public Builder clearQuantity() {
          
          quantity_ = 0;
          onChanged();
          return this;
        }

        private int measure_ = 0;
        /**
         * <code>.recipes.Recipe.IngredientMeasure measure = 3;</code>
         */
        public int getMeasureValue() {
          return measure_;
        }
        /**
         * <code>.recipes.Recipe.IngredientMeasure measure = 3;</code>
         */
        public Builder setMeasureValue(int value) {
          measure_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.recipes.Recipe.IngredientMeasure measure = 3;</code>
         */
        public com.gb.recipes.RecipeInformation.Recipe.IngredientMeasure getMeasure() {
          @SuppressWarnings("deprecation")
          com.gb.recipes.RecipeInformation.Recipe.IngredientMeasure result = com.gb.recipes.RecipeInformation.Recipe.IngredientMeasure.valueOf(measure_);
          return result == null ? com.gb.recipes.RecipeInformation.Recipe.IngredientMeasure.UNRECOGNIZED : result;
        }
        /**
         * <code>.recipes.Recipe.IngredientMeasure measure = 3;</code>
         */
        public Builder setMeasure(com.gb.recipes.RecipeInformation.Recipe.IngredientMeasure value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          measure_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.recipes.Recipe.IngredientMeasure measure = 3;</code>
         */
        public Builder clearMeasure() {
          
          measure_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:recipes.Recipe.Ingredient)
      }

      // @@protoc_insertion_point(class_scope:recipes.Recipe.Ingredient)
      private static final com.gb.recipes.RecipeInformation.Recipe.Ingredient DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.gb.recipes.RecipeInformation.Recipe.Ingredient();
      }

      public static com.gb.recipes.RecipeInformation.Recipe.Ingredient getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Ingredient>
          PARSER = new com.google.protobuf.AbstractParser<Ingredient>() {
        @java.lang.Override
        public Ingredient parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Ingredient(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Ingredient> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Ingredient> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.gb.recipes.RecipeInformation.Recipe.Ingredient getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREP_TIME_FIELD_NUMBER = 3;
    private int prepTime_;
    /**
     * <code>int32 prep_time = 3;</code>
     */
    public int getPrepTime() {
      return prepTime_;
    }

    public static final int COOK_TIME_FIELD_NUMBER = 4;
    private int cookTime_;
    /**
     * <code>int32 cook_time = 4;</code>
     */
    public int getCookTime() {
      return cookTime_;
    }

    public static final int RATING_FIELD_NUMBER = 5;
    private int rating_;
    /**
     * <code>int32 rating = 5;</code>
     */
    public int getRating() {
      return rating_;
    }

    public static final int INGREDIENTS_FIELD_NUMBER = 6;
    private java.util.List<com.gb.recipes.RecipeInformation.Recipe.Ingredient> ingredients_;
    /**
     * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
     */
    public java.util.List<com.gb.recipes.RecipeInformation.Recipe.Ingredient> getIngredientsList() {
      return ingredients_;
    }
    /**
     * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
     */
    public java.util.List<? extends com.gb.recipes.RecipeInformation.Recipe.IngredientOrBuilder> 
        getIngredientsOrBuilderList() {
      return ingredients_;
    }
    /**
     * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
     */
    public int getIngredientsCount() {
      return ingredients_.size();
    }
    /**
     * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
     */
    public com.gb.recipes.RecipeInformation.Recipe.Ingredient getIngredients(int index) {
      return ingredients_.get(index);
    }
    /**
     * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
     */
    public com.gb.recipes.RecipeInformation.Recipe.IngredientOrBuilder getIngredientsOrBuilder(
        int index) {
      return ingredients_.get(index);
    }

    public static final int CUISINE_FIELD_NUMBER = 7;
    private int cuisine_;
    /**
     * <code>.recipes.Recipe.Cuisine cuisine = 7;</code>
     */
    public int getCuisineValue() {
      return cuisine_;
    }
    /**
     * <code>.recipes.Recipe.Cuisine cuisine = 7;</code>
     */
    public com.gb.recipes.RecipeInformation.Recipe.Cuisine getCuisine() {
      @SuppressWarnings("deprecation")
      com.gb.recipes.RecipeInformation.Recipe.Cuisine result = com.gb.recipes.RecipeInformation.Recipe.Cuisine.valueOf(cuisine_);
      return result == null ? com.gb.recipes.RecipeInformation.Recipe.Cuisine.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (prepTime_ != 0) {
        output.writeInt32(3, prepTime_);
      }
      if (cookTime_ != 0) {
        output.writeInt32(4, cookTime_);
      }
      if (rating_ != 0) {
        output.writeInt32(5, rating_);
      }
      for (int i = 0; i < ingredients_.size(); i++) {
        output.writeMessage(6, ingredients_.get(i));
      }
      if (cuisine_ != com.gb.recipes.RecipeInformation.Recipe.Cuisine.SOUTH_INDIAN.getNumber()) {
        output.writeEnum(7, cuisine_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (prepTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, prepTime_);
      }
      if (cookTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, cookTime_);
      }
      if (rating_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, rating_);
      }
      for (int i = 0; i < ingredients_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, ingredients_.get(i));
      }
      if (cuisine_ != com.gb.recipes.RecipeInformation.Recipe.Cuisine.SOUTH_INDIAN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, cuisine_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gb.recipes.RecipeInformation.Recipe)) {
        return super.equals(obj);
      }
      com.gb.recipes.RecipeInformation.Recipe other = (com.gb.recipes.RecipeInformation.Recipe) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && (getPrepTime()
          == other.getPrepTime());
      result = result && (getCookTime()
          == other.getCookTime());
      result = result && (getRating()
          == other.getRating());
      result = result && getIngredientsList()
          .equals(other.getIngredientsList());
      result = result && cuisine_ == other.cuisine_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PREP_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getPrepTime();
      hash = (37 * hash) + COOK_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getCookTime();
      hash = (37 * hash) + RATING_FIELD_NUMBER;
      hash = (53 * hash) + getRating();
      if (getIngredientsCount() > 0) {
        hash = (37 * hash) + INGREDIENTS_FIELD_NUMBER;
        hash = (53 * hash) + getIngredientsList().hashCode();
      }
      hash = (37 * hash) + CUISINE_FIELD_NUMBER;
      hash = (53 * hash) + cuisine_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gb.recipes.RecipeInformation.Recipe parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gb.recipes.RecipeInformation.Recipe parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gb.recipes.RecipeInformation.Recipe parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gb.recipes.RecipeInformation.Recipe parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gb.recipes.RecipeInformation.Recipe parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gb.recipes.RecipeInformation.Recipe parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gb.recipes.RecipeInformation.Recipe parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gb.recipes.RecipeInformation.Recipe parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gb.recipes.RecipeInformation.Recipe parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gb.recipes.RecipeInformation.Recipe parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gb.recipes.RecipeInformation.Recipe parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gb.recipes.RecipeInformation.Recipe parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gb.recipes.RecipeInformation.Recipe prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code recipes.Recipe}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:recipes.Recipe)
        com.gb.recipes.RecipeInformation.RecipeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gb.recipes.RecipeInformation.internal_static_recipes_Recipe_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gb.recipes.RecipeInformation.internal_static_recipes_Recipe_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gb.recipes.RecipeInformation.Recipe.class, com.gb.recipes.RecipeInformation.Recipe.Builder.class);
      }

      // Construct using com.gb.recipes.RecipeInformation.Recipe.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getIngredientsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        prepTime_ = 0;

        cookTime_ = 0;

        rating_ = 0;

        if (ingredientsBuilder_ == null) {
          ingredients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          ingredientsBuilder_.clear();
        }
        cuisine_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gb.recipes.RecipeInformation.internal_static_recipes_Recipe_descriptor;
      }

      @java.lang.Override
      public com.gb.recipes.RecipeInformation.Recipe getDefaultInstanceForType() {
        return com.gb.recipes.RecipeInformation.Recipe.getDefaultInstance();
      }

      @java.lang.Override
      public com.gb.recipes.RecipeInformation.Recipe build() {
        com.gb.recipes.RecipeInformation.Recipe result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gb.recipes.RecipeInformation.Recipe buildPartial() {
        com.gb.recipes.RecipeInformation.Recipe result = new com.gb.recipes.RecipeInformation.Recipe(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.prepTime_ = prepTime_;
        result.cookTime_ = cookTime_;
        result.rating_ = rating_;
        if (ingredientsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            ingredients_ = java.util.Collections.unmodifiableList(ingredients_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.ingredients_ = ingredients_;
        } else {
          result.ingredients_ = ingredientsBuilder_.build();
        }
        result.cuisine_ = cuisine_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gb.recipes.RecipeInformation.Recipe) {
          return mergeFrom((com.gb.recipes.RecipeInformation.Recipe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gb.recipes.RecipeInformation.Recipe other) {
        if (other == com.gb.recipes.RecipeInformation.Recipe.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getPrepTime() != 0) {
          setPrepTime(other.getPrepTime());
        }
        if (other.getCookTime() != 0) {
          setCookTime(other.getCookTime());
        }
        if (other.getRating() != 0) {
          setRating(other.getRating());
        }
        if (ingredientsBuilder_ == null) {
          if (!other.ingredients_.isEmpty()) {
            if (ingredients_.isEmpty()) {
              ingredients_ = other.ingredients_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureIngredientsIsMutable();
              ingredients_.addAll(other.ingredients_);
            }
            onChanged();
          }
        } else {
          if (!other.ingredients_.isEmpty()) {
            if (ingredientsBuilder_.isEmpty()) {
              ingredientsBuilder_.dispose();
              ingredientsBuilder_ = null;
              ingredients_ = other.ingredients_;
              bitField0_ = (bitField0_ & ~0x00000020);
              ingredientsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getIngredientsFieldBuilder() : null;
            } else {
              ingredientsBuilder_.addAllMessages(other.ingredients_);
            }
          }
        }
        if (other.cuisine_ != 0) {
          setCuisineValue(other.getCuisineValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gb.recipes.RecipeInformation.Recipe parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gb.recipes.RecipeInformation.Recipe) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int prepTime_ ;
      /**
       * <code>int32 prep_time = 3;</code>
       */
      public int getPrepTime() {
        return prepTime_;
      }
      /**
       * <code>int32 prep_time = 3;</code>
       */
      public Builder setPrepTime(int value) {
        
        prepTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 prep_time = 3;</code>
       */
      public Builder clearPrepTime() {
        
        prepTime_ = 0;
        onChanged();
        return this;
      }

      private int cookTime_ ;
      /**
       * <code>int32 cook_time = 4;</code>
       */
      public int getCookTime() {
        return cookTime_;
      }
      /**
       * <code>int32 cook_time = 4;</code>
       */
      public Builder setCookTime(int value) {
        
        cookTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cook_time = 4;</code>
       */
      public Builder clearCookTime() {
        
        cookTime_ = 0;
        onChanged();
        return this;
      }

      private int rating_ ;
      /**
       * <code>int32 rating = 5;</code>
       */
      public int getRating() {
        return rating_;
      }
      /**
       * <code>int32 rating = 5;</code>
       */
      public Builder setRating(int value) {
        
        rating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 rating = 5;</code>
       */
      public Builder clearRating() {
        
        rating_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.gb.recipes.RecipeInformation.Recipe.Ingredient> ingredients_ =
        java.util.Collections.emptyList();
      private void ensureIngredientsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          ingredients_ = new java.util.ArrayList<com.gb.recipes.RecipeInformation.Recipe.Ingredient>(ingredients_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gb.recipes.RecipeInformation.Recipe.Ingredient, com.gb.recipes.RecipeInformation.Recipe.Ingredient.Builder, com.gb.recipes.RecipeInformation.Recipe.IngredientOrBuilder> ingredientsBuilder_;

      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public java.util.List<com.gb.recipes.RecipeInformation.Recipe.Ingredient> getIngredientsList() {
        if (ingredientsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ingredients_);
        } else {
          return ingredientsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public int getIngredientsCount() {
        if (ingredientsBuilder_ == null) {
          return ingredients_.size();
        } else {
          return ingredientsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public com.gb.recipes.RecipeInformation.Recipe.Ingredient getIngredients(int index) {
        if (ingredientsBuilder_ == null) {
          return ingredients_.get(index);
        } else {
          return ingredientsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public Builder setIngredients(
          int index, com.gb.recipes.RecipeInformation.Recipe.Ingredient value) {
        if (ingredientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIngredientsIsMutable();
          ingredients_.set(index, value);
          onChanged();
        } else {
          ingredientsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public Builder setIngredients(
          int index, com.gb.recipes.RecipeInformation.Recipe.Ingredient.Builder builderForValue) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          ingredients_.set(index, builderForValue.build());
          onChanged();
        } else {
          ingredientsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public Builder addIngredients(com.gb.recipes.RecipeInformation.Recipe.Ingredient value) {
        if (ingredientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIngredientsIsMutable();
          ingredients_.add(value);
          onChanged();
        } else {
          ingredientsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public Builder addIngredients(
          int index, com.gb.recipes.RecipeInformation.Recipe.Ingredient value) {
        if (ingredientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIngredientsIsMutable();
          ingredients_.add(index, value);
          onChanged();
        } else {
          ingredientsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public Builder addIngredients(
          com.gb.recipes.RecipeInformation.Recipe.Ingredient.Builder builderForValue) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          ingredients_.add(builderForValue.build());
          onChanged();
        } else {
          ingredientsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public Builder addIngredients(
          int index, com.gb.recipes.RecipeInformation.Recipe.Ingredient.Builder builderForValue) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          ingredients_.add(index, builderForValue.build());
          onChanged();
        } else {
          ingredientsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public Builder addAllIngredients(
          java.lang.Iterable<? extends com.gb.recipes.RecipeInformation.Recipe.Ingredient> values) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ingredients_);
          onChanged();
        } else {
          ingredientsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public Builder clearIngredients() {
        if (ingredientsBuilder_ == null) {
          ingredients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          ingredientsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public Builder removeIngredients(int index) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          ingredients_.remove(index);
          onChanged();
        } else {
          ingredientsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public com.gb.recipes.RecipeInformation.Recipe.Ingredient.Builder getIngredientsBuilder(
          int index) {
        return getIngredientsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public com.gb.recipes.RecipeInformation.Recipe.IngredientOrBuilder getIngredientsOrBuilder(
          int index) {
        if (ingredientsBuilder_ == null) {
          return ingredients_.get(index);  } else {
          return ingredientsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public java.util.List<? extends com.gb.recipes.RecipeInformation.Recipe.IngredientOrBuilder> 
           getIngredientsOrBuilderList() {
        if (ingredientsBuilder_ != null) {
          return ingredientsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ingredients_);
        }
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public com.gb.recipes.RecipeInformation.Recipe.Ingredient.Builder addIngredientsBuilder() {
        return getIngredientsFieldBuilder().addBuilder(
            com.gb.recipes.RecipeInformation.Recipe.Ingredient.getDefaultInstance());
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public com.gb.recipes.RecipeInformation.Recipe.Ingredient.Builder addIngredientsBuilder(
          int index) {
        return getIngredientsFieldBuilder().addBuilder(
            index, com.gb.recipes.RecipeInformation.Recipe.Ingredient.getDefaultInstance());
      }
      /**
       * <code>repeated .recipes.Recipe.Ingredient ingredients = 6;</code>
       */
      public java.util.List<com.gb.recipes.RecipeInformation.Recipe.Ingredient.Builder> 
           getIngredientsBuilderList() {
        return getIngredientsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.gb.recipes.RecipeInformation.Recipe.Ingredient, com.gb.recipes.RecipeInformation.Recipe.Ingredient.Builder, com.gb.recipes.RecipeInformation.Recipe.IngredientOrBuilder> 
          getIngredientsFieldBuilder() {
        if (ingredientsBuilder_ == null) {
          ingredientsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.gb.recipes.RecipeInformation.Recipe.Ingredient, com.gb.recipes.RecipeInformation.Recipe.Ingredient.Builder, com.gb.recipes.RecipeInformation.Recipe.IngredientOrBuilder>(
                  ingredients_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          ingredients_ = null;
        }
        return ingredientsBuilder_;
      }

      private int cuisine_ = 0;
      /**
       * <code>.recipes.Recipe.Cuisine cuisine = 7;</code>
       */
      public int getCuisineValue() {
        return cuisine_;
      }
      /**
       * <code>.recipes.Recipe.Cuisine cuisine = 7;</code>
       */
      public Builder setCuisineValue(int value) {
        cuisine_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.recipes.Recipe.Cuisine cuisine = 7;</code>
       */
      public com.gb.recipes.RecipeInformation.Recipe.Cuisine getCuisine() {
        @SuppressWarnings("deprecation")
        com.gb.recipes.RecipeInformation.Recipe.Cuisine result = com.gb.recipes.RecipeInformation.Recipe.Cuisine.valueOf(cuisine_);
        return result == null ? com.gb.recipes.RecipeInformation.Recipe.Cuisine.UNRECOGNIZED : result;
      }
      /**
       * <code>.recipes.Recipe.Cuisine cuisine = 7;</code>
       */
      public Builder setCuisine(com.gb.recipes.RecipeInformation.Recipe.Cuisine value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cuisine_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.recipes.Recipe.Cuisine cuisine = 7;</code>
       */
      public Builder clearCuisine() {
        
        cuisine_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:recipes.Recipe)
    }

    // @@protoc_insertion_point(class_scope:recipes.Recipe)
    private static final com.gb.recipes.RecipeInformation.Recipe DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gb.recipes.RecipeInformation.Recipe();
    }

    public static com.gb.recipes.RecipeInformation.Recipe getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Recipe>
        PARSER = new com.google.protobuf.AbstractParser<Recipe>() {
      @java.lang.Override
      public Recipe parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Recipe(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Recipe> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Recipe> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gb.recipes.RecipeInformation.Recipe getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recipes_Recipe_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recipes_Recipe_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recipes_Recipe_Ingredient_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recipes_Recipe_Ingredient_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027resources/recipes.proto\022\007recipes\"\212\003\n\006R" +
      "ecipe\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\021\n\tprep_" +
      "time\030\003 \001(\005\022\021\n\tcook_time\030\004 \001(\005\022\016\n\006rating\030" +
      "\005 \001(\005\022/\n\013ingredients\030\006 \003(\0132\032.recipes.Rec" +
      "ipe.Ingredient\022(\n\007cuisine\030\007 \001(\0162\027.recipe" +
      "s.Recipe.Cuisine\032`\n\nIngredient\022\014\n\004name\030\001" +
      " \001(\t\022\020\n\010quantity\030\002 \001(\005\0222\n\007measure\030\003 \001(\0162" +
      "!.recipes.Recipe.IngredientMeasure\"D\n\021In" +
      "gredientMeasure\022\010\n\004EACH\020\000\022\t\n\005OUCES\020\001\022\007\n\003" +
      "LBS\020\002\022\t\n\005GRAMS\020\003\022\006\n\002ML\020\004\"-\n\007Cuisine\022\020\n\014S" +
      "OUTH_INDIAN\020\000\022\020\n\014NORTH_INDIAN\020\001B#\n\016com.g" +
      "b.recipesB\021RecipeInformationb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_recipes_Recipe_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_recipes_Recipe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recipes_Recipe_descriptor,
        new java.lang.String[] { "Id", "Name", "PrepTime", "CookTime", "Rating", "Ingredients", "Cuisine", });
    internal_static_recipes_Recipe_Ingredient_descriptor =
      internal_static_recipes_Recipe_descriptor.getNestedTypes().get(0);
    internal_static_recipes_Recipe_Ingredient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recipes_Recipe_Ingredient_descriptor,
        new java.lang.String[] { "Name", "Quantity", "Measure", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
